### ISSUE TITLE
Write API documentation

### ISSUE THREAD

**Issue by retrixe** [retrixe/octyne#7]
Some initial work has started in API.md for now, but documentation is far from complete.

- [x] Document reverse proxying and security practices to follow with Octyne.
- [x] Complete documenting all endpoints with parameters and responses.
- [ ] Document possible error responses.

**Comment by chaneth8** [comment]
Hi, I'd love to help with this issue but I'm having some problems getting your APIs to run. 

What I've done so far is to move config.json and users.json into the same directory as main.go. I then ran the following in the terminal: 
<img width="502" alt="Screen Shot 2022-05-08 at 4 10 47 PM" src="https://user-images.githubusercontent.com/83342511/167314033-76540091-bcd3-4624-b091-c0bbe80c1789.png">

The errors I got were: 
# command-line-arguments
./main.go:17:22: undefined: Config
./main.go:36:13: undefined: Config
./main.go:55:15: undefined: InitializeConnector
./main.go:61:6: undefined: CreateProcess

I'm wondering how to resolve these errors, so that the code will run? 

Thanks so much!

**Comment by retrixe** [comment]
@chaneth8 it should run correctly with `go run .`

`go run main.go` will only compile `main.go` and ignore all the other Go files.

Alternatively, you can use any of the uploaded binaries on the releases page instead if you don't want to run from source.

**Comment by chaneth8** [comment]
@retrixe Thank you for getting back. Is it okay if I ask a few more questions? 

I'm trying to test the API on postman to get an idea of what it outputs for each endpoint. But I'm running into some trouble getting the authentication token. When I ran the following, I got: 

<img width="825" alt="Screen Shot 2022-05-15 at 3 14 53 PM" src="https://user-images.githubusercontent.com/83342511/168489997-73e781c0-7c16-479a-b737-8f7640c4c6e4.png">

Do I need to be running an app with octyne in order to log in? If so, how do I do that? 

Or do I need to edit users.json? This is what I have currently: 
<img width="419" alt="Screen Shot 2022-05-15 at 3 15 05 PM" src="https://user-images.githubusercontent.com/83342511/168490003-c3a0c953-05ab-4608-a108-714be3ab9e52.png">

Thanks.

**Comment by Sanguineous1** [comment]
@chaneth8 You are passing the login details through query parameters, you need to pass them through headers as `Username` and `Password` for logging in.

Also for users.json yes you do need to modify it, replace `username` with your username of choice and the password with a SHA256 hash, you can convert your password to a hash at https://sha256.vercel.app/

**Comment by retrixe** [comment]
Complete with 1.2.0, documenting potential API errors is too much for now.
